# Generated by Django 6.0 on 2025-12-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_achievement_mission_userprofile_global_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fluency_score',
            field=models.IntegerField(default=0, help_text='Oral Fluency Score 0-100'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vocabulary_score',
            field=models.IntegerField(default=0, help_text='Vocabulary Mastery Score 0-100'),
        ),
    ]
